###
GET http://localhost:1337/

###
POST http://localhost:1337/
Content-Type: application/json

{
  "name": "John Doe",
  "location": "San Francisco"
}

###
GET http://localhost:1337/setup

###
GET http://tower.local:1337/setup

###
POST http://tower.local:1337/
Content-Type: application/json

{
  "name": "Jane Doe",
  "location": "San Francisco"
}